#!/usr/bin/env bash
set -e

x=5
y=10
echo "$x and $y"


source ~/my_project/tf4_gpu/bin/activate
cd /home/ali/my_project/models-master/research
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
cd -

python train.py --logtostderr --train_dir=./models/train --pipeline_config_path=ssd_mobilenet_v2_quant_sean.config

# jupyter notebook
